config/routes.rb
Rails.application.routes.draw do
  devise_for :rto_officers, controllers: {
    registrations: 'rto_officers/registrations'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#home'
  resources :vehicles do
    get 'download_emission_records', on: :member, to: 'vehicles#download_emission_records'
    get :approve_vehicle, on: :member
    get :search, on: :collection
  end


  namespace :api do
    namespace :v1 do
      post '/vehicle_records', to: 'vehicle_records#create'
    end
  end

end

app/models/vehicle.rb
# frozen_string_literal: true
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :emission_records

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  require 'prawn'
  before_action :authenticate_user!, if: :user_signed_in?
  before_action :authenticate_rto_officer!, only: %i[pending_verification show search], if: :rto_officer_signed_in?
  before_action :set_vehicle, only: %i[show edit update destroy download_emission_records]

  def index
    if user_signed_in?
      @vehicles = Vehicle.all
    elsif rto_officer_signed_in?
      @vehicles = Vehicle.where(status: true).all
    end
  end

  def show
    # Step 1: Fetch and parse the data
    records = @vehicle.emission_records
    data = records.map do |record|
      {
        time: record.created_at.time,
        co2: record.carbon_dioxide,
        co: record.carbon_monoxide,
        air_quality: record.air_quality
      }
    end

    # Step 2: Group the data by minute and capture the highest value
    grouped_data = data.group_by { |record| record[:time].ago(1.minute) }
    highest_values = grouped_data.transform_values do |group|
      {
        co2: group.max_by { |record| record[:co2] }[:co2],
        co: group.max_by { |record| record[:co] }[:co],
        air_quality: group.max_by { |record| record[:air_quality] }[:air_quality]
      }
    end

    # Step 3: Prepare the data for Chartkick
    @chart_data = {
      labels: highest_values.keys.map { |minute| minute.strftime('%Y-%m-%d %H:%M:%S') },
      datasets: [
        { name: 'CO2', data: highest_values.values.map { |record| [record[:time], record[:co2]] } },
        { name: 'CO', data: highest_values.values.map { |record| [record[:time], record[:co]] } },
        { name: 'Air Quality', data: highest_values.values.map { |record| [record[:time], record[:air_quality]] } }
      ]
    }

    @emission_records = records.limit(50)
  end

  def new
    @vehicle = Vehicle.new
  end

  def edit
  end

  def update
    if @vehicle.update(vehicle_params)
      redirect_to vehicles_path
    else
      render :edit
    end
  end

  def create
    @vehicle = Vehicle.create(vehicle_params.merge(user_id: current_user.id))
    if @vehicle.save
      redirect_to vehicles_path, notice: 'Vehicle added successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @vehicle.destroy
    redirect_to vehicles_path, notice: 'Destroyed the vehicle and data'
  end

  def search
    if params[:vehicle_number].present?
      @vehicle = Vehicle.find_by(vehicle_number: params[:vehicle_number].strip)
    end

    if @vehicle
      redirect_to vehicle_path(@vehicle)
    else
      redirect_to vehicles_path, notice: 'Vehicle not found'
    end
  end

  # Show the list of vehicles that are over polluting the atmosphere

  def approve_vehicle
    @vehicle.update(status: false)

    redirect_to vehicles_path, notice: 'Vehicle approved'
  end

  def download_emission_records
    respond_to do |format|
      format.pdf do
        pdf = EmissionRecordsPdf.new(@vehicle)  # Create the PDF instance
        send_data pdf.render, filename: 'emission_records.pdf', type: 'application/pdf'
      end
    end
  end


  private

  def vehicle_params
    params.require(:vehicle).permit(:vehicle_model, :vehicle_number, :vehicle_type, :status, :devise_id)
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end
end

app/views/vehicles/_form.html.erb
<div class="w-50 col-8 offset-2">
  <%= form_with model: @vehicle, method: :post, data: { turbo_stream: false } do |f| %>

    <%= f.label :vehicle_model, class: 'form-label' %>
    <%= f.text_field :vehicle_model, class: 'form-control' %>

    <%= f.label :vehicle_number, class: 'form-label' %>
    <%= f.text_field :vehicle_number, class: 'form-control' %>

    <%= f.label :devise_id, class: 'form-label' %>
    <%= f.text_field :devise_id, class: 'form-control' %>

    <%= f.hidden_field :status, value: false %>

    <%= f.label :vehicle_type, class: 'form-label' %><br>
    <%= f.radio_button :vehicle_type, "car" %> Car
    <%= f.radio_button :vehicle_type, "bike"%> Bike
    <br>
    <div class="mt-2">
      <%= f.submit 'Create', class: 'btn btn-primary' %>
      <%= link_to "Back", vehicles_path, class: "btn btn-secondary"  %>
    </div>

  <% end %>
</div>

app/views/vehicles/edit.html.erb
<%= render 'vehicles/form' %>

app/views/vehicles/index.html.erb
<!-- vehicle list -->
<div class="container-fluid">
  <!-- vehicle search -->
  <% if @vehicles.present? %>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <%= form_with url: search_vehicles_path, method: :get do |form| %>
          <div class="d-md-flex d-lg-flex d-sm-block flex-sm-row mt-sm-2">
            <%= form.text_field :vehicle_number, class: "form-control me-sm-2 me-lg-2 w-sm-50", placeholder: "Enter Vehicle Number" %>
            <%= form.submit "Search", class: "btn btn-outline-success" %>
          </div>
        <% end %>
      </div>
    </nav>

    <div class="container-fluid ">
      <div class="row mt-1 p-1">
        <div class="col-6">
          <h4>Vehicle Number</h4>
        </div>
      </div>

      <% @vehicles.each do |vehicle| %>
        <div class="row mt-1 p-1 border-bottom">
          <!-- for vehicle number -->
          <div class="col-md-6 col-lg-6">
            <span><%= vehicle.vehicle_number %></span>
            <span style="color: blue; font-size: small"><%= vehicle.vehicle_type %></span>
          </div>
          <!-- for view page button -->
          <div class="col-3 btn-group btn-group-sm">
            <%= link_to "edit", edit_vehicle_path(vehicle), class: "btn btn-warning" %>
            <%= link_to "show", vehicle_path(vehicle), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3 class="mt-2 text-center" style="color: red">
      No records found...
    </h3>
  <% end %>
</div>

app/views/vehicles/new.html.erb
<%= render 'vehicles/form' %>

app/views/vehicles/show.html.erb
<div class="container-fluid">
  <% if @emission_records.present? %>
  <div class="row">
    <div class="mt-2 col-8">
    <% if rto_officer_signed_in? %>
        <strong class="me-2">Approve Vehicle : </strong><%= link_to "Approve", approve_vehicle_vehicle_path(@vehicle), data: {  }, class: "btn btn-sm btn-primary"  %>
    <% end %>
    </div>
    <div class="text-end col-4">
      <%= link_to "Download Record", download_emission_records_vehicle_url(@vehicle, format: :pdf), class: "text-end btn btn-sm btn-secondary" %>
    </div>
  </div>
  <div class="table-responsive table-fixed-header">

        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Carbon dioxide</th>
              <th>Carbon monoxide</th>
              <th>Air Quality</th>
              <th>Timestamp</th>
            </tr>
          </thead>

      <tbody>
      <% id = 0 %>
      <% @emission_records&.each do |record| %>
      <tr>
        <% id = id + 1 %>
        <td><%=  id  %></td>
        <td><%= record.carbon_dioxide %></td>
        <td><%=  record.carbon_monoxide  %></td>
        <td><%= record.air_quality %></td>
        <td><%=  record.created_at  %></td>
      </tr>
      <%  end  %>
      </tbody>
    </table>

  </div>
  <!-- for graph and chart -->
  <div class="container-fluid">

    <%# @emission = EmissionRecord.all.limit(50) %>
<!--    <div class="Co2-partial col-8 offset-2">-->
<!--      <h3>Carbon dioxide</h3>-->
<!--      <div>-->

<!--      </div>-->
<!--    </div>-->
<!--    <div class="Co-partial col-6 offset-2">-->
<!--      <h3>Carbon monoxide</h3>-->
<!--      <div>-->
        <%#= line_chart [[2,4], [3,5], [4,6]] %>
<!--      </div>-->
<!--    </div>-->
  <% else %>
    <div class="mt-2 text-end d-flex justify-content-center align-items-center">
      <strong class="me-2">Approve Vehicle : </strong><%= link_to "Approve", approve_vehicle_vehicle_path(@vehicle), data: {  }, class: "btn btn-primary"  %>
    </div>
    <h3 class="mt-2 text-center" style="color: red">
      No records found...
    </h3>
  <%  end %>
  </div>

</div>
<style>
    .table-fixed-header {
        overflow: auto;
        max-height: 85vh;
    }
    .table-fixed-header thead {
        position: sticky;
        top: 0;
        background-color: #fff;
    }
</style>