config/routes.rb
Rails.application.routes.draw do
  devise_for :rto_officers, controllers: {
    registrations: 'rto_officers/registrations'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#home'
  resources :vehicles do
    get 'download_emission_records', on: :member, to: 'vehicles#download_emission_records'
    get :approve_vehicle, on: :member
    get :search, on: :collection
  end


  namespace :api do
    namespace :v1 do
      post '/vehicle_records', to: 'vehicle_records#create'
    end
  end

end

app/views/layouts/_navbar_Rto_officer.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Emission Monitoring System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_rto_officer_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Vehicles", vehicles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pending Approval", vehicles_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <div class="ms-auto">
      <%= link_to "logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-outline-danger" %>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_user.html.erb
<nav class="navbar navbar-expand-md navbar-expand-lg bg-body-tertiary sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Emission Monitoring System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Vehicles", vehicles_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= edit_user_registration_path %>">Edit Profile</a>
          </li>
          <li class="nav-item">
            <%= link_to new_vehicle_path, class: "btn btn-sm btn-primary" do %>
              <i class="bi bi-plus-lg"> Add Vehicle</i>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Login
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "User Login", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "RTO Login", new_rto_officer_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "Admin Register", new_rto_officer_registration_path, class: "dropdown-item" %></li>
              <li><%= link_to "Register", new_user_registration_path, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <div class=" ms-auto">
          <%= link_to "sign out", destroy_user_session_path, data: { turbo_method: :delete}, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmissionMonitoring</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <% if flash[:notice].present? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
    <%= render "layouts/navbar_user" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/rto_officer.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmissionMonitoring</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body>
<%= render "layouts/navbar_Rto_officer" %>
<%= yield %>
</body>
</html>